# -*- coding: utf-8 -*-
"""for chat-bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Du7AxS82YNfIdLzRfl7yCT0cjF5op-d
"""

import pandas as pd
import numpy as np
import datetime
import requests
from io import BytesIO

# загрузка эксель файла из githab
url = "https://github.com/EkaterinaIsupova/chat-bot/raw/main/List_of_deadlines3.xlsx"
response = requests.get(url)
df_org = pd.read_excel(BytesIO(response.content))
df_org.head(5)

# ф-я возвращает 5 переменных, соответсвующих 5и столбцам эксель таблицы
def pandas_dataframe(data):
  task = data['task']
  if not isinstance(task, str):
    raise TypeError("поле 'task' должно быть типа str")

  descr = data['description']
  if not isinstance(descr, str):
    raise TypeError("поле 'description' должно быть типа int")

  deadline = datetime.datetime.strptime(str(data['date/time']), '%Y-%m-%d %H:%M:%S')
  if not isinstance(deadline, datetime.date):
    raise TypeError("поле 'deadline' должно быть типа datetime")

  for sentence in data['receiverse']:
    words = sentence.split()
  particip = data['receiverse'].split()
  if not isinstance(particip, list):
    raise TypeError("поле 'receiverse' должно быть типа list")

  return {'task': task, 'description': descr, 'date/time': deadline, 'receiverse': particip}

for i in range(0, len(df_org.index)-1):
  print(pandas_dataframe(df_org.iloc[i]))

# ф-я добавляет новое "задание" в дата фрейм
def pandas_dataframe(task: str, descr: str, deadline: datetime, particip: list):
  df_org.loc[len(df_org.index)] = [task, descr, deadline, particip]

pandas_dataframe("njkfgnkd", "fjkndjf", "2024-04-25 10:15:00", '@nscs, @dkjcn')
df_org